CREATE TABLE `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TEAMS_ID` INT NOT NULL,
  `REF_VOLUNTEERS_POSITION_ID` INT NOT NULL,
  `QTY` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TEAMS_VOLUNTEERS_TEMPLATE_1_idx` (`TEAMS_ID` ASC) VISIBLE,
  INDEX `fk_TEAMS_VOLUNTEERS_TEMPLATE_2_idx` (`REF_VOLUNTEERS_POSITION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TEAMS_VOLUNTEERS_TEMPLATE_1`
    FOREIGN KEY (`TEAMS_ID`)
    REFERENCES `runner_lite`.`TEAMS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TEAMS_VOLUNTEERS_TEMPLATE_2`
    FOREIGN KEY (`REF_VOLUNTEERS_POSITION_ID`)
    REFERENCES `runner_lite`.`REF_VOLUNTEERS_POSITION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (`TEAMS_ID`, `REF_VOLUNTEERS_POSITION_ID`, `QTY`) VALUES ('1', '2', '1');
INSERT INTO `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (`TEAMS_ID`, `REF_VOLUNTEERS_POSITION_ID`, `QTY`) VALUES ('1', '3', '2');
INSERT INTO `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (`TEAMS_ID`, `REF_VOLUNTEERS_POSITION_ID`, `QTY`) VALUES ('1', '4', '2');
INSERT INTO `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (`TEAMS_ID`, `REF_VOLUNTEERS_POSITION_ID`, `QTY`) VALUES ('1', '6', '1');
INSERT INTO `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (`TEAMS_ID`, `REF_VOLUNTEERS_POSITION_ID`, `QTY`) VALUES ('2', '1', '1');
INSERT INTO `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (`TEAMS_ID`, `REF_VOLUNTEERS_POSITION_ID`, `QTY`) VALUES ('2', '2', '1');
INSERT INTO `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (`TEAMS_ID`, `REF_VOLUNTEERS_POSITION_ID`, `QTY`) VALUES ('2', '6', '1');
INSERT INTO `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (`TEAMS_ID`, `REF_VOLUNTEERS_POSITION_ID`, `QTY`) VALUES ('2', '7', '1');
INSERT INTO `runner_lite`.`TEAMS_VOLUNTEERS_TEMPLATE` (`TEAMS_ID`, `REF_VOLUNTEERS_POSITION_ID`, `QTY`) VALUES ('2', '8', '2');

